# Generated by Django 2.0.1 on 2018-01-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('name', 'version', 'url')},
        ),
    ]
